name: celilac_life
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  flutter_markdown: ^0.7.0
  auto_size_text: ^3.0.0
  responsive_builder: ^0.5.0
  animated_text_kit: ^4.2.2
  flutter_keyboard_visibility: ^6.0.0
  font_awesome_flutter: ^10.4.0
  lottie: ^3.3.2
  flutter_dotenv: ^5.0.2
  supabase_flutter: ^2.10.3
  gpt_markdown: ^1.1.4
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.0.0
  async_button_builder: ^3.0.0+1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/images/onboarding/background_on_boarding.png
    - assets/images/onboarding/on_boarding_01.png
    - assets/images/onboarding/image_splashscreen.png
    - assets/images/onboarding/profissional_gastronomico.png
    - assets/images/onboarding/sensitivity.png
    - assets/images/onboarding/trigo.png
    - assets/images/onboarding/background_blue.png
    - assets/images/onboarding/background_grey.png
    - assets/images/onboarding/
    - assets/policies/
    - assets/md/use_terms_and_privacy.md
    - assets/images/splashscreen/
    - assets/images/splashscreen/splashscreen_light.png
    - assets/images/splashscreen/splashscreen_dark.png

    # Lotties
    - assets/lotties/welcome.json

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/brand/icon_light.png"
  adaptive_icon_background: "assets/images/brand/icon_light.png"
  adaptive_icon_foreground: "assets/images/brand/icon_light.png"